// Generated by Supabase CLI

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      User: {
        Row: {
          id: string
          email: string
          name: string | null
          createdAt: string
        }
        Insert: {
          id?: string
          email: string
          name?: string | null
          createdAt?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          createdAt?: string
        }
        Relationships: []
      }
      LearningTask: {
        Row: {
          id: string
          title: string
          kpiTech: string | null
          kpiConcept: string | null
          presenter: string
          affiliation: string | null
          date: string
          userId: string
        }
        Insert: {
          id?: string
          title: string
          kpiTech?: string | null
          kpiConcept?: string | null
          presenter: string
          affiliation?: string | null
          date: string
          userId: string
        }
        Update: {
          id?: string
          title?: string
          kpiTech?: string | null
          kpiConcept?: string | null
          presenter?: string
          affiliation?: string | null
          date?: string
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "LearningTask_userId_fkey"
            columns: ["userId"]
            referencedRelation: "User"
            referencedColumns: ["id"]
          }
        ]
      }
      procedures: {
        Row: {
          id: string
          name: string
          description: string
          presenter: string
          affiliation: string
          date: string
          kpi_tech: string[]
          kpi_concept: string[]
          transcript: string
          yaml_content: string | null
          simulation_settings: Json | null
          created_at: string
          updated_at: string
          user_id: string | null
        }
        Insert: {
          id?: string
          name: string
          description: string
          presenter: string
          affiliation: string
          date: string
          kpi_tech?: string[]
          kpi_concept?: string[]
          transcript?: string
          yaml_content?: string | null
          simulation_settings?: Json | null
          created_at?: string
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          id?: string
          name?: string
          description?: string
          presenter?: string
          affiliation?: string
          date?: string
          kpi_tech?: string[]
          kpi_concept?: string[]
          transcript?: string
          yaml_content?: string | null
          simulation_settings?: Json | null
          created_at?: string
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "procedures_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "User"
            referencedColumns: ["id"]
          }
        ]
      }
      media_items: {
        Row: {
          id: string
          procedure_id: string
          name: string
          type: string
          url: string
          size: string
          created_at: string
        }
        Insert: {
          id?: string
          procedure_id: string
          name: string
          type: string
          url: string
          size: string
          created_at?: string
        }
        Update: {
          id?: string
          procedure_id?: string
          name?: string
          type?: string
          url?: string
          size?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "media_items_procedure_id_fkey"
            columns: ["procedure_id"]
            referencedRelation: "procedures"
            referencedColumns: ["id"]
          }
        ]
      }
      steps: {
        Row: {
          id: string
          procedure_id: string
          content: string
          comments: string[]
          order: number
          created_at: string
        }
        Insert: {
          id?: string
          procedure_id: string
          content: string
          comments?: string[]
          order: number
          created_at?: string
        }
        Update: {
          id?: string
          procedure_id?: string
          content?: string
          comments?: string[]
          order?: number
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "steps_procedure_id_fkey"
            columns: ["procedure_id"]
            referencedRelation: "procedures"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      MediaType: "IMAGE" | "VIDEO" | "AUDIO" | "PDF"
      SuggestionType: "INSERTION" | "CLARIFYING_QUESTION" | "MCQ" | "OPEN_ENDED"
      QuestionType: "MCQ" | "OPEN_ENDED"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
} 