// Generated by Supabase CLI

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      User: {
        Row: {
          id: string
          email: string
          name: string | null
          createdAt: string
        }
        Insert: {
          id?: string
          email: string
          name?: string | null
          createdAt?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          createdAt?: string
        }
        Relationships: []
      }
      LearningTask: {
        Row: {
          id: string
          title: string
          kpiTech: string | null
          kpiConcept: string | null
          presenter: string
          affiliation: string | null
          date: string
          userId: string
        }
        Insert: {
          id?: string
          title: string
          kpiTech?: string | null
          kpiConcept?: string | null
          presenter: string
          affiliation?: string | null
          date: string
          userId: string
        }
        Update: {
          id?: string
          title?: string
          kpiTech?: string | null
          kpiConcept?: string | null
          presenter?: string
          affiliation?: string | null
          date?: string
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "LearningTask_userId_fkey"
            columns: ["userId"]
            referencedRelation: "User"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      MediaType: "IMAGE" | "VIDEO" | "AUDIO" | "PDF"
      SuggestionType: "INSERTION" | "CLARIFYING_QUESTION" | "MCQ" | "OPEN_ENDED"
      QuestionType: "MCQ" | "OPEN_ENDED"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
} 