// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcoyezbndmfjfmikwjie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjb3llemJuZG1mamZtaWt3amllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODEzOTEsImV4cCI6MjA2MTQ1NzM5MX0.HK2QP9e031eMB6Jqm79NA2RXiW6yOh3oyHRVPJKKA5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});